### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [brunoit/prj-rev-bwfs-dasmoto#6]
https://github.com/brunoit/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Resources/CSS/Index.css#L30

Use the universal selector * to avoid repeating the font-family in every style.

```css
* {
  font-family: Helvetica;
}
```

Avoid repetition wherever possible.
